### ISSUE TITLE
nested plugin/feature support

### ISSUE THREAD

**Issue by shahabganji** [shahabganji/multiple_plugins#1]
A few days ago I came up with an idea of creating an aurelia plugin named aurelia-toolbelt, which includes many custom elements, value converters and so on. Having said that, I want it to be configured in a way that developers using this plugin be able to use the plugin a s a whole or partially.
For instance, in their ```boot``` or ```main``` file the use it as the followings: 
``` js
aurelia.use.plugin( PLATFORM.moduleName('aurelia-toolbelt') );
```
which will enable the usage of all the components in the package, or
``` js
aurelia.use.plugin( PLATFORM.moduleName('aurelia-toolbelt/components') );
```
which will include all the components(read custom elements :wink: ), or
``` js
aurelia.use.plugin( PLATFORM.moduleName('aurelia-toolbelt/components/component-one') );
```
needless to say that it enables only that specified component.

however I faced encounter errors that I have no idea why they are happening, in this repository which I am trying to simulate what I really want.

I would be grateful if anyone can help this out.

use ```dotnet run``` to run the project.

**Comment by shahabganji** [comment]
@vegarringdal 

I had this idea for the skeleton, but because i faced problems I created this repository to test it with ```feature```, however based on your changes [here](https://github.com/vegarringdal/skeleton-plugin-typescript) i guess it would be more convenient to change this repository. any idea?

**Comment by vegarringdal** [comment]
You want to do something like what materialize/kendo bridges does here ->
https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/blob/master/src/index.js
https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/blob/master/src/config-builder.js

**Comment by shahabganji** [comment]
@vegarringdal 

I'll take a look and test that on my repo, thanks :+1:

**Comment by shahabganji** [comment]
@vegarringdal  

That works, however its kind of a module aggregator and not precisely what I want. It is so messy and after a while  will become full of ```.useX``` methods, which is a burden for developers to handle/use the methods. 

Moreover, based on above-mentioned request I expect webpack not to bring all the JavaScript for all modules when I just add a nested plugin, such as 
```
aurelia.use.plugin( PLATFORM.moduleName('aurelia-toolbelt/components/component-one') );
```
while in 
>https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/blob/master/src/index.js
https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/blob/master/src/config-builder.js

it will bring all the source codes :-1: .

I do want to know whether what I said above is possible or not. I guess maybe @EisenbergEffect or @jods4 can come up with a solution. Not sure though :weary:

**Comment by vegarringdal** [comment]
Would be nice if we could just do this: 
`import('aurelia-toolbelt/components/component-one').then( /*some code to load it*/)`
And own bundle would have been made for this...

Wonder if its possible to make Aurelia work without the "aurelia-loader" , so we dont need a webpack loader, a fusebox loader etc etc

I guess we would need a extra method for components to returning the html content. But in that one we could have used require()/import() or just have the text content in js code(kinda like to have html in html files)

I know very little about webpack/ bundling etc etc, but is it just me, or is passing eveything though the aurelia-loader kinda getting in the way ?

**Comment by shahabganji** [comment]
> I guess we would need a extra method for components to returning the html content.

I think you write the following code any where in your ```.ts/.js``` files, will do that, if not mistaking

```
PLATFORM.moduleName( 'path_to_your_html' );
```
>  is passing eveything though the aurelia-loader kinda getting in the way ?

I think aurelia-webpack-loader is kinda getting in the way

**Comment by vegarringdal** [comment]
Does it split into own bundle/load async if this is used?
`PLATFORM.moduleName( 'path_to_your_html' );`

I dont see how the bundler know this without a lot of work/ special custom solution between framework and loader(webpack/fusebox/systemjs).

I kinda hope aurelia 2.0 will have more options to skip built in loader and let something like fusebox do its work by just use require()/import(), so I could delete the fusebox-aurleia-loader package.

That way quantum/rollups/code splitting would would right away (I think)

Maybe I just dont understand it enough :-)
Been wrong before.

**Comment by vegarringdal** [comment]
@shahabganji 
fyi
https://github.com/fuse-box/fuse-box-aurelia-loader/issues/30

**Comment by jods4** [comment]
@vegarringdal Remember Aurelia was started years ago. At that time there was no standard for loading modules (i.e. `import`, static or dynamic) and bundlers were quite different. AMD/requirejs was king, bower was still a package manager for the front end... Webpack and rollup wouldn't be a thing before a long while, with SystemJS making a splash just before.

At that point, `aurelia-loader` was meant to be an abstraction over your preferred loader: could be requirejs, commonjs inside node, systemjs or maybe even no bundle at all during dev. So that the same code would work no matter what API you used to load modules.

I think that it was a good intention, given the landscape at the time.

Problem is that newer bundlers work very differently. 
Aurelia has several dependencies on module exports and even module names. Those things don't work well with scope hoisting, or tree shaking or even just modules and exports renaming.

`aurelia-loader` is also very opaque to bundlers. It's not a well known API such as `import`. In a sense you can say that it gets in the way, yes.

If Aurelia 2.0 makes breaking changes, I'm confident that it will drop `aurelia-loader` in favor of the now standard `import` apis, as well as take into consideration modern tooling.

**Comment by jods4** [comment]
@shahabganji I had a quick glance at your code, this line strikes me as incorrect:
https://github.com/shahabganji/multiple_plugins/blob/master/ClientApp/resources/index.ts#L6

`components/index` is an absolute path that doesn't exist, it should fail at compilation, shouldn't it?

**Comment by vegarringdal** [comment]
@jods4

Thx, like I said there is a lot I do not know when it comes to bundling/loaders.
Do you know if there have there been any talk about aurelia 2.0 alpha/beta work, or just a todo list?
Would be nice to know :-)

**Comment by jods4** [comment]
@vegarringdal as far as I know there have been talks about improvements that needs serious breaking changes, with the implication that they should all be done in a batch for some 2.0 release. I don't think any actual work towards a 2.0 has started yet. Compatibility and v1.x are still on top!

**Comment by shahabganji** [comment]
@jods4  

I worte that line in three different way:

```
  config.feature(PLATFORM.moduleName('./components'));
```
this and the one you said have run-time error indication that it can't find ```module with ID: ./components/index```
and when I write as the following I get the same error at a compile time 
```
 config.feature(PLATFORM.moduleName('components'));
```

**PS:** as far as I remember for the feature and plugin methods both writing the ```index``` file and not writing are the same, aren't they?

**Comment by shahabganji** [comment]
@vegarringdal 

> Does it split into own bundle/load async if this is used?
PLATFORM.moduleName( 'path_to_your_html' );

Not that one :arrow_up: but as far as I know ```webpack``` only load those modules you used in your project not all the modules added via ```npm``` or ```yarn```. that's why I want the above-mentioned separation and don't like the way materialized organized the project.

**Comment by shahabganji** [comment]
@vegarringdal 

> fuse-box/fuse-box-aurelia-loader#30

What I understand of them is code splitting and bundling/minifying the final ```.js``` file, am I right? If yes then take a look at these :point_down: 

* https://webpack.js.org/guides/code-splitting/
* https://webpack.js.org/guides/tree-shaking/
* https://webpack.js.org/guides/production/

However, most of my friends are in favor of fusebox API rather than webpack config file :blink:

**Comment by shahabganji** [comment]
@jods4 

I changed the line to 
https://github.com/shahabganji/multiple_plugins/blob/master/ClientApp/resources/index.ts#L6

and I have also changed nested folders to absolote path.

It seems to me that ```feature``` method works only with absolute path and not relatives, am I right?

Anyway, when I'm using absolute path for all the neseted plugin folders everything works just as well.


@vegarringdal now when you use 
```
aurelia.use.developmentLogging()
            .feature(PLATFORM.moduleName('resources/components/first-component/index'));
```
the source for ```second-component``` plugin will not be bundles or included in the final ```.js``` file, which I guess is something you want, right?

**Comment by vegarringdal** [comment]
@shahabganji 

>```
aurelia.use.developmentLogging().feature(PLATFORM.moduleName('resources/components/first-component/index'));```

>the source for second-component plugin will not be bundles or included in the final .js file, which I guess is something you want, right?

I guess I mostly wanted the fusebox magic to just work, but that wont happend before 2.0 :-)
Im no bundling expert at all, only reason why I used time on the [fusebox-aurelia-loader](https://github.com/fuse-box/fuse-box-aurelia-loader) is because Fusebox gave me the same feeling I got when I saw the first Aurelia video.
> WOW that look fun and easy to use !!!

Only bad part about Fusebox in the beginning was the type checking, I kinda gotten used to typescript helping me. That's the reason why I started on this project: [fusebox-typechecker](https://github.com/vegarringdal/fuse-box-typechecker). I think its pretty nice now, even have tslint now.

Else Ive been working on a [vGrid](https://github.com/vegarringdal/vGrid) project, rebuilding and rebuilding, last rebuild I manage to get grouping/locked columns working. its kinda like a never ending project since I learn a lot while doing it, and always want to change/rebuild stuff, but I will just call it v 1.0.0 withing next weeks after Ive tested it a little more for major bugs.

**Comment by jods4** [comment]
> It seems to me that feature method works only with absolute path and not relatives, am I right?
Anyway, when I'm using absolute path for all the nested plugin folders everything works just as well.
Thanks 🙏

The problem with relative paths is that they must normalize the same way in Webpack and in Aurelia and the runtime resolution is not always in an obvious context. It can be surprising and tricky. 
When using Webpack, I generally advise to stick with absolute paths in your code, that just works.

> Does it split into own bundle/load async if this is used?
PLATFORM.moduleName( 'path_to_your_html' );

You can split there if you want, use 
```js
PLATFORM.moduleName('some_module', 'chunk_name')
```
This is documented here: https://github.com/aurelia/webpack-plugin/wiki/Managing-dependencies#code-splitting

So can we close this issue?

**Comment by shahabganji** [comment]
Thanks for your complete answer @jods4
